name: Build and Publish

on:
    push:
        branches: ['integration/youtube']
    release:
        types: ['published']

jobs:
    push:
        name: Build and Publish Docker Image
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v4

            - name: Configure QEMU for Multi-Architecture Builds
              uses: docker/setup-qemu-action@v3

            - name: Set Up Docker Buildx with Platform Support
              uses: docker/setup-buildx-action@v3
              with:
                  platforms: linux/amd64,linux/arm64

            - name: Authenticate with Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push Multi-Platform Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  push: true
                  tags: taranovegor/tomsg_bot:yt-shorts
                  platforms: linux/amd64,linux/arm64
                  build-args: VERSION=yt-shorts
